### ISSUE TITLE
Avoid including plugins inline

### ISSUE THREAD

**Issue by josephting** [jerry54604/scheduler.js#1]
Hello @jerry54604 :grin:

**Comment by jerry54604** [comment]
Hi @josephting 😅

**Comment by josephting** [comment]
Pro @jerry54604, pro scheduler :open_mouth:

**Comment by chlimappspace** [comment]
dun be so lazy split the file

**Comment by josephting** [comment]
ya lo, no split file I thought Scheduler is part of jQuery. :sweat_smile:

**Comment by jerry54604** [comment]
too lazy 😪

**Comment by josephting** [comment]
@chlimappspace Help submit PR lol
